# Generated by Django 4.1.5 on 2023-02-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('income', 'Входящяя'), ('outgoing', 'Исходщяя')], max_length=10),
        ),
    ]
