# Generated by Django 4.1.5 on 2023-04-12 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_alter_transaction_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='slug',
        ),
    ]
