# Generated by Django 4.1.5 on 2023-05-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0006_transactionimport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('income', 'Входящая'), ('outgoing', 'Исходщая')], max_length=10, verbose_name='Тип транзакции'),
        ),
    ]
