# Generated by Django 4.1.5 on 2023-05-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0008_transaction_finances_transaction_transaction_type_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('income', 'Входящая'), ('outgoing', 'Исходящая')], max_length=10, verbose_name='Тип транзакции'),
        ),
    ]
