# Generated by Django 4.1.5 on 2023-05-24 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0011_alter_transaction_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date'], 'verbose_name': 'Транзакция', 'verbose_name_plural': 'Транзакции'},
        ),
    ]
