# Generated by Django 4.1.5 on 2023-08-07 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0013_category_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='color',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
